# Use an official Python runtime as a parent image
FROM alpine

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

RUN apk update
RUN apk add python py-pip
RUN pip install --trusted-host pypi.python.org -r requirements.txt
RUN apk add libcrypto1.1 --update-cache --repository http://dl-3.alpinelinux.org/alpine/edge/main/ --allow-untrusted
RUN apk add gdal --update-cache --repository http://dl-3.alpinelinux.org/alpine/edge/testing/ --allow-untrusted

